[package]
name = "stl-split"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stl = "0.2.1"
clap = { version = "4.0", features = ["derive"] }
ordered-float = "3.7.0"
